name: cryptowl
description: "A local-first encrypted vault for storing sensitive information."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  sqlite3: ^2.9.4
  ffi: ^2.1.3
  native_argon2:
    path: deps/native_argon2
  native_sqlcipher:
    path: deps/native_sqlcipher
  uuid: ^4.5.1
  drift: ^2.28.2
  convert: ^3.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  introduction_screen: ^4.0.0
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18
  go_router: ^16.3.0
  logging: ^1.3.0
  toastification: ^3.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flex_color_scheme: ^8.4.0
  responsive_framework: ^1.5.1
  intl: ^0.20.2
  flutter_adaptive_scaffold: ^0.3.3+1
  package_info_plus: ^8.3.1
  radio_group_v2: ^3.3.1
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^2.6.1
  fleather: ^1.27.0
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  remixicon: ^1.4.1
  base32: ^2.2.0
  flutter_secure_storage: ^10.3.1
  file_saver: ^0.3.1
  pdf: ^3.11.3
  cryptography: ^2.9.0
  cryptography_flutter: ^2.3.4
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.14
  drift_dev: ^2.28.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  faker: ^2.2.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/dict/
  fonts:
    - family: LXGWWenKai
      fonts:
        - asset: assets/fonts/lxgw-wenkai-v1.520/LXGWWenKai-Light.ttf
          weight: 300
        - asset: assets/fonts/lxgw-wenkai-v1.520/LXGWWenKai-Regular.ttf
          weight: 400
        - asset: assets/fonts/lxgw-wenkai-v1.520/LXGWWenKai-Medium.ttf
          weight: 500
