// Mocks generated by Mockito 5.4.6 from annotations
// in cryptowl/test/services/app_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:io' as _i2;
import 'dart:typed_data' as _i15;

import 'package:cryptowl/src/config/app_config.dart' as _i8;
import 'package:cryptowl/src/crypto/aead_crypto.dart' as _i5;
import 'package:cryptowl/src/crypto/argon2.dart' as _i4;
import 'package:cryptowl/src/crypto/hkdf.dart' as _i3;
import 'package:cryptowl/src/crypto/hmac.dart' as _i10;
import 'package:cryptowl/src/crypto/protected_value.dart' as _i7;
import 'package:cryptowl/src/service/config_service.dart' as _i6;
import 'package:cryptowl/src/service/file_service.dart' as _i12;
import 'package:cryptowl/src/service/kdf_service.dart' as _i14;
import 'package:cryptowl/src/service/version_service.dart' as _i11;
import 'package:logging/logging.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCryptoGraphyHkdf_1 extends _i1.SmartFake
    implements _i3.CryptoGraphyHkdf {
  _FakeCryptoGraphyHkdf_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNativeArgon2_2 extends _i1.SmartFake implements _i4.NativeArgon2 {
  _FakeNativeArgon2_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCryptographyAesGcm_3 extends _i1.SmartFake
    implements _i5.CryptographyAesGcm {
  _FakeCryptographyAesGcm_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfigService_4 extends _i1.SmartFake implements _i6.ConfigService {
  _FakeConfigService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProtectedValue_5 extends _i1.SmartFake
    implements _i7.ProtectedValue {
  _FakeProtectedValue_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthEncryptedResult_6 extends _i1.SmartFake
    implements _i5.AuthEncryptedResult {
  _FakeAuthEncryptedResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppConfig_7 extends _i1.SmartFake implements _i8.AppConfig {
  _FakeAppConfig_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogger_8 extends _i1.SmartFake implements _i9.Logger {
  _FakeLogger_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCryptoHmac_9 extends _i1.SmartFake implements _i10.CryptoHmac {
  _FakeCryptoHmac_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVersionService_10 extends _i1.SmartFake
    implements _i11.VersionService {
  _FakeVersionService_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileService extends _i1.Mock implements _i12.FileService {
  @override
  _i13.Future<void> copyJiebaDicts() =>
      (super.noSuchMethod(
            Invocation.method(#copyJiebaDicts, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<String>> getSqlcipherInstances() =>
      (super.noSuchMethod(
            Invocation.method(#getSqlcipherInstances, []),
            returnValue: _i13.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i13.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i13.Future<List<String>>);

  @override
  _i13.Future<_i2.File> getConfigFile(String? instanceId) =>
      (super.noSuchMethod(
            Invocation.method(#getConfigFile, [instanceId]),
            returnValue: _i13.Future<_i2.File>.value(
              _FakeFile_0(
                this,
                Invocation.method(#getConfigFile, [instanceId]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i2.File>.value(
              _FakeFile_0(
                this,
                Invocation.method(#getConfigFile, [instanceId]),
              ),
            ),
          )
          as _i13.Future<_i2.File>);

  @override
  _i13.Future<void> writeFile(String? content, String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#writeFile, [content, fileName]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [KdfService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKdfService extends _i1.Mock implements _i14.KdfService {
  @override
  _i3.CryptoGraphyHkdf get hkdf =>
      (super.noSuchMethod(
            Invocation.getter(#hkdf),
            returnValue: _FakeCryptoGraphyHkdf_1(
              this,
              Invocation.getter(#hkdf),
            ),
            returnValueForMissingStub: _FakeCryptoGraphyHkdf_1(
              this,
              Invocation.getter(#hkdf),
            ),
          )
          as _i3.CryptoGraphyHkdf);

  @override
  _i4.NativeArgon2 get argon2 =>
      (super.noSuchMethod(
            Invocation.getter(#argon2),
            returnValue: _FakeNativeArgon2_2(this, Invocation.getter(#argon2)),
            returnValueForMissingStub: _FakeNativeArgon2_2(
              this,
              Invocation.getter(#argon2),
            ),
          )
          as _i4.NativeArgon2);

  @override
  _i5.CryptographyAesGcm get aeadCrypto =>
      (super.noSuchMethod(
            Invocation.getter(#aeadCrypto),
            returnValue: _FakeCryptographyAesGcm_3(
              this,
              Invocation.getter(#aeadCrypto),
            ),
            returnValueForMissingStub: _FakeCryptographyAesGcm_3(
              this,
              Invocation.getter(#aeadCrypto),
            ),
          )
          as _i5.CryptographyAesGcm);

  @override
  _i6.ConfigService get configService =>
      (super.noSuchMethod(
            Invocation.getter(#configService),
            returnValue: _FakeConfigService_4(
              this,
              Invocation.getter(#configService),
            ),
            returnValueForMissingStub: _FakeConfigService_4(
              this,
              Invocation.getter(#configService),
            ),
          )
          as _i6.ConfigService);

  @override
  _i13.Future<_i7.ProtectedValue> createTransformedMasterKey(
    _i7.ProtectedValue? masterPassword,
    _i7.ProtectedValue? secretKey,
    _i15.Uint8List? salt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTransformedMasterKey, [
              masterPassword,
              secretKey,
              salt,
            ]),
            returnValue: _i13.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_5(
                this,
                Invocation.method(#createTransformedMasterKey, [
                  masterPassword,
                  secretKey,
                  salt,
                ]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_5(
                this,
                Invocation.method(#createTransformedMasterKey, [
                  masterPassword,
                  secretKey,
                  salt,
                ]),
              ),
            ),
          )
          as _i13.Future<_i7.ProtectedValue>);

  @override
  _i13.Future<_i7.ProtectedValue> createStretchedMasterKey(
    _i7.ProtectedValue? transformedMasterKey,
    _i15.Uint8List? instanceId,
    _i15.Uint8List? masterSeed,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStretchedMasterKey, [
              transformedMasterKey,
              instanceId,
              masterSeed,
            ]),
            returnValue: _i13.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_5(
                this,
                Invocation.method(#createStretchedMasterKey, [
                  transformedMasterKey,
                  instanceId,
                  masterSeed,
                ]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_5(
                this,
                Invocation.method(#createStretchedMasterKey, [
                  transformedMasterKey,
                  instanceId,
                  masterSeed,
                ]),
              ),
            ),
          )
          as _i13.Future<_i7.ProtectedValue>);

  @override
  _i13.Future<_i5.AuthEncryptedResult> createProtectedSymmetricKey(
    _i7.ProtectedValue? symmetricKey,
    _i7.ProtectedValue? stretchedMasterKey,
    _i15.Uint8List? nonce,
    _i15.Uint8List? instanceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createProtectedSymmetricKey, [
              symmetricKey,
              stretchedMasterKey,
              nonce,
              instanceId,
            ]),
            returnValue: _i13.Future<_i5.AuthEncryptedResult>.value(
              _FakeAuthEncryptedResult_6(
                this,
                Invocation.method(#createProtectedSymmetricKey, [
                  symmetricKey,
                  stretchedMasterKey,
                  nonce,
                  instanceId,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i13.Future<_i5.AuthEncryptedResult>.value(
                  _FakeAuthEncryptedResult_6(
                    this,
                    Invocation.method(#createProtectedSymmetricKey, [
                      symmetricKey,
                      stretchedMasterKey,
                      nonce,
                      instanceId,
                    ]),
                  ),
                ),
          )
          as _i13.Future<_i5.AuthEncryptedResult>);

  @override
  _i13.Future<String> generateUUID() =>
      (super.noSuchMethod(
            Invocation.method(#generateUUID, []),
            returnValue: _i13.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#generateUUID, []),
              ),
            ),
            returnValueForMissingStub: _i13.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#generateUUID, []),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<_i7.ProtectedValue> generateRandomBytes({int? length = 32}) =>
      (super.noSuchMethod(
            Invocation.method(#generateRandomBytes, [], {#length: length}),
            returnValue: _i13.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_5(
                this,
                Invocation.method(#generateRandomBytes, [], {#length: length}),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_5(
                this,
                Invocation.method(#generateRandomBytes, [], {#length: length}),
              ),
            ),
          )
          as _i13.Future<_i7.ProtectedValue>);

  @override
  _i13.Future<_i8.AppConfig> generateAppConfig(
    _i7.ProtectedValue? masterPassword,
    _i7.ProtectedValue? secretKey,
    String? instanceId,
    _i15.Uint8List? transformSeed,
    _i15.Uint8List? masterSeed,
    _i7.ProtectedValue? symmetricKey,
    _i15.Uint8List? nonce,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateAppConfig, [
              masterPassword,
              secretKey,
              instanceId,
              transformSeed,
              masterSeed,
              symmetricKey,
              nonce,
            ]),
            returnValue: _i13.Future<_i8.AppConfig>.value(
              _FakeAppConfig_7(
                this,
                Invocation.method(#generateAppConfig, [
                  masterPassword,
                  secretKey,
                  instanceId,
                  transformSeed,
                  masterSeed,
                  symmetricKey,
                  nonce,
                ]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i8.AppConfig>.value(
              _FakeAppConfig_7(
                this,
                Invocation.method(#generateAppConfig, [
                  masterPassword,
                  secretKey,
                  instanceId,
                  transformSeed,
                  masterSeed,
                  symmetricKey,
                  nonce,
                ]),
              ),
            ),
          )
          as _i13.Future<_i8.AppConfig>);

  @override
  _i13.Future<_i7.ProtectedValue> decryptSymmetricKey(
    _i7.ProtectedValue? masterPassword,
    _i7.ProtectedValue? secretKey,
    _i8.AppConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptSymmetricKey, [
              masterPassword,
              secretKey,
              config,
            ]),
            returnValue: _i13.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_5(
                this,
                Invocation.method(#decryptSymmetricKey, [
                  masterPassword,
                  secretKey,
                  config,
                ]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_5(
                this,
                Invocation.method(#decryptSymmetricKey, [
                  masterPassword,
                  secretKey,
                  config,
                ]),
              ),
            ),
          )
          as _i13.Future<_i7.ProtectedValue>);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i6.ConfigService {
  @override
  _i9.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_8(this, Invocation.getter(#logger)),
            returnValueForMissingStub: _FakeLogger_8(
              this,
              Invocation.getter(#logger),
            ),
          )
          as _i9.Logger);

  @override
  _i10.CryptoHmac get hmac =>
      (super.noSuchMethod(
            Invocation.getter(#hmac),
            returnValue: _FakeCryptoHmac_9(this, Invocation.getter(#hmac)),
            returnValueForMissingStub: _FakeCryptoHmac_9(
              this,
              Invocation.getter(#hmac),
            ),
          )
          as _i10.CryptoHmac);

  @override
  _i11.VersionService get versionService =>
      (super.noSuchMethod(
            Invocation.getter(#versionService),
            returnValue: _FakeVersionService_10(
              this,
              Invocation.getter(#versionService),
            ),
            returnValueForMissingStub: _FakeVersionService_10(
              this,
              Invocation.getter(#versionService),
            ),
          )
          as _i11.VersionService);

  @override
  _i13.Future<_i8.AppConfig> loadConfig(String? content) =>
      (super.noSuchMethod(
            Invocation.method(#loadConfig, [content]),
            returnValue: _i13.Future<_i8.AppConfig>.value(
              _FakeAppConfig_7(this, Invocation.method(#loadConfig, [content])),
            ),
            returnValueForMissingStub: _i13.Future<_i8.AppConfig>.value(
              _FakeAppConfig_7(this, Invocation.method(#loadConfig, [content])),
            ),
          )
          as _i13.Future<_i8.AppConfig>);

  @override
  _i13.Future<bool> verifyConfig(
    _i8.AppConfig? config,
    _i7.ProtectedValue? macKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyConfig, [config, macKey]),
            returnValue: _i13.Future<bool>.value(false),
            returnValueForMissingStub: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<_i8.AppConfig> createConfig(
    String? instanceId,
    _i15.Uint8List? transformSeed,
    _i15.Uint8List? masterSeed,
    _i5.AuthEncryptedResult? protectedSymmetricKey,
    _i7.ProtectedValue? macKey,
    _i15.Uint8List? nonce,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConfig, [
              instanceId,
              transformSeed,
              masterSeed,
              protectedSymmetricKey,
              macKey,
              nonce,
            ]),
            returnValue: _i13.Future<_i8.AppConfig>.value(
              _FakeAppConfig_7(
                this,
                Invocation.method(#createConfig, [
                  instanceId,
                  transformSeed,
                  masterSeed,
                  protectedSymmetricKey,
                  macKey,
                  nonce,
                ]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<_i8.AppConfig>.value(
              _FakeAppConfig_7(
                this,
                Invocation.method(#createConfig, [
                  instanceId,
                  transformSeed,
                  masterSeed,
                  protectedSymmetricKey,
                  macKey,
                  nonce,
                ]),
              ),
            ),
          )
          as _i13.Future<_i8.AppConfig>);

  @override
  _i13.Future<String> saveConfig(_i8.AppConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#saveConfig, [config]),
            returnValue: _i13.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#saveConfig, [config]),
              ),
            ),
            returnValueForMissingStub: _i13.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#saveConfig, [config]),
              ),
            ),
          )
          as _i13.Future<String>);

  @override
  _i13.Future<_i7.ProtectedValue?> readSecureStore(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#readSecureStore, [key]),
            returnValue: _i13.Future<_i7.ProtectedValue?>.value(),
            returnValueForMissingStub: _i13.Future<_i7.ProtectedValue?>.value(),
          )
          as _i13.Future<_i7.ProtectedValue?>);

  @override
  _i13.Future<void> saveSecureStore(String? key, _i7.ProtectedValue? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveSecureStore, [key, data]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<_i15.Uint8List> generateEmergencyKit(String? secretKey) =>
      (super.noSuchMethod(
            Invocation.method(#generateEmergencyKit, [secretKey]),
            returnValue: _i13.Future<_i15.Uint8List>.value(_i15.Uint8List(0)),
            returnValueForMissingStub: _i13.Future<_i15.Uint8List>.value(
              _i15.Uint8List(0),
            ),
          )
          as _i13.Future<_i15.Uint8List>);
}
