// Mocks generated by Mockito 5.4.6 from annotations
// in cryptowl/test/services/password_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:typed_data' as _i12;

import 'package:cryptowl/src/config/app_config.dart' as _i8;
import 'package:cryptowl/src/crypto/aead_crypto.dart' as _i5;
import 'package:cryptowl/src/crypto/argon2.dart' as _i4;
import 'package:cryptowl/src/crypto/hkdf.dart' as _i3;
import 'package:cryptowl/src/crypto/protected_value.dart' as _i7;
import 'package:cryptowl/src/service/config_service.dart' as _i6;
import 'package:cryptowl/src/service/kdf_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:riverpod/src/internals.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProviderContainer_0 extends _i1.SmartFake
    implements _i2.ProviderContainer {
  _FakeProviderContainer_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeepAliveLink_1 extends _i1.SmartFake implements _i2.KeepAliveLink {
  _FakeKeepAliveLink_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProviderSubscription_2<State1> extends _i1.SmartFake
    implements _i2.ProviderSubscription<State1> {
  _FakeProviderSubscription_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCryptoGraphyHkdf_3 extends _i1.SmartFake
    implements _i3.CryptoGraphyHkdf {
  _FakeCryptoGraphyHkdf_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNativeArgon2_4 extends _i1.SmartFake implements _i4.NativeArgon2 {
  _FakeNativeArgon2_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCryptographyAesGcm_5 extends _i1.SmartFake
    implements _i5.CryptographyAesGcm {
  _FakeCryptographyAesGcm_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfigService_6 extends _i1.SmartFake implements _i6.ConfigService {
  _FakeConfigService_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProtectedValue_7 extends _i1.SmartFake
    implements _i7.ProtectedValue {
  _FakeProtectedValue_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthEncryptedResult_8 extends _i1.SmartFake
    implements _i5.AuthEncryptedResult {
  _FakeAuthEncryptedResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppConfig_9 extends _i1.SmartFake implements _i8.AppConfig {
  _FakeAppConfig_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Ref].
///
/// See the documentation for Mockito's code generation for more information.
class MockRef<State extends Object?> extends _i1.Mock
    implements _i2.Ref<State> {
  @override
  _i2.ProviderContainer get container =>
      (super.noSuchMethod(
            Invocation.getter(#container),
            returnValue: _FakeProviderContainer_0(
              this,
              Invocation.getter(#container),
            ),
            returnValueForMissingStub: _FakeProviderContainer_0(
              this,
              Invocation.getter(#container),
            ),
          )
          as _i2.ProviderContainer);

  @override
  T refresh<T>(_i2.Refreshable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [provider]),
            returnValue: _i9.dummyValue<T>(
              this,
              Invocation.method(#refresh, [provider]),
            ),
            returnValueForMissingStub: _i9.dummyValue<T>(
              this,
              Invocation.method(#refresh, [provider]),
            ),
          )
          as T);

  @override
  void invalidate(_i2.ProviderOrFamily? provider) => super.noSuchMethod(
    Invocation.method(#invalidate, [provider]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void listenSelf(
    void Function(State?, State)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateSelf() => super.noSuchMethod(
    Invocation.method(#invalidateSelf, []),
    returnValueForMissingStub: null,
  );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onAddListener, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onRemoveListener, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onResume, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onCancel, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onDispose, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  T read<T>(_i2.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#read, [provider]),
            returnValue: _i9.dummyValue<T>(
              this,
              Invocation.method(#read, [provider]),
            ),
            returnValueForMissingStub: _i9.dummyValue<T>(
              this,
              Invocation.method(#read, [provider]),
            ),
          )
          as T);

  @override
  bool exists(_i2.ProviderBase<Object?>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [provider]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  T watch<T>(_i2.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [provider]),
            returnValue: _i9.dummyValue<T>(
              this,
              Invocation.method(#watch, [provider]),
            ),
            returnValueForMissingStub: _i9.dummyValue<T>(
              this,
              Invocation.method(#watch, [provider]),
            ),
          )
          as T);

  @override
  _i2.KeepAliveLink keepAlive() =>
      (super.noSuchMethod(
            Invocation.method(#keepAlive, []),
            returnValue: _FakeKeepAliveLink_1(
              this,
              Invocation.method(#keepAlive, []),
            ),
            returnValueForMissingStub: _FakeKeepAliveLink_1(
              this,
              Invocation.method(#keepAlive, []),
            ),
          )
          as _i2.KeepAliveLink);

  @override
  _i2.ProviderSubscription<T> listen<T>(
    _i2.ProviderListenable<T>? provider,
    void Function(T?, T)? listener, {
    void Function(Object, StackTrace)? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [provider, listener],
              {#onError: onError, #fireImmediately: fireImmediately},
            ),
            returnValue: _FakeProviderSubscription_2<T>(
              this,
              Invocation.method(
                #listen,
                [provider, listener],
                {#onError: onError, #fireImmediately: fireImmediately},
              ),
            ),
            returnValueForMissingStub: _FakeProviderSubscription_2<T>(
              this,
              Invocation.method(
                #listen,
                [provider, listener],
                {#onError: onError, #fireImmediately: fireImmediately},
              ),
            ),
          )
          as _i2.ProviderSubscription<T>);
}

/// A class which mocks [KdfService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKdfService extends _i1.Mock implements _i10.KdfService {
  @override
  _i3.CryptoGraphyHkdf get hkdf =>
      (super.noSuchMethod(
            Invocation.getter(#hkdf),
            returnValue: _FakeCryptoGraphyHkdf_3(
              this,
              Invocation.getter(#hkdf),
            ),
            returnValueForMissingStub: _FakeCryptoGraphyHkdf_3(
              this,
              Invocation.getter(#hkdf),
            ),
          )
          as _i3.CryptoGraphyHkdf);

  @override
  _i4.NativeArgon2 get argon2 =>
      (super.noSuchMethod(
            Invocation.getter(#argon2),
            returnValue: _FakeNativeArgon2_4(this, Invocation.getter(#argon2)),
            returnValueForMissingStub: _FakeNativeArgon2_4(
              this,
              Invocation.getter(#argon2),
            ),
          )
          as _i4.NativeArgon2);

  @override
  _i5.CryptographyAesGcm get aeadCrypto =>
      (super.noSuchMethod(
            Invocation.getter(#aeadCrypto),
            returnValue: _FakeCryptographyAesGcm_5(
              this,
              Invocation.getter(#aeadCrypto),
            ),
            returnValueForMissingStub: _FakeCryptographyAesGcm_5(
              this,
              Invocation.getter(#aeadCrypto),
            ),
          )
          as _i5.CryptographyAesGcm);

  @override
  _i6.ConfigService get configService =>
      (super.noSuchMethod(
            Invocation.getter(#configService),
            returnValue: _FakeConfigService_6(
              this,
              Invocation.getter(#configService),
            ),
            returnValueForMissingStub: _FakeConfigService_6(
              this,
              Invocation.getter(#configService),
            ),
          )
          as _i6.ConfigService);

  @override
  _i11.Future<_i7.ProtectedValue> createTransformedMasterKey(
    _i7.ProtectedValue? masterPassword,
    _i7.ProtectedValue? secretKey,
    _i12.Uint8List? salt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTransformedMasterKey, [
              masterPassword,
              secretKey,
              salt,
            ]),
            returnValue: _i11.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_7(
                this,
                Invocation.method(#createTransformedMasterKey, [
                  masterPassword,
                  secretKey,
                  salt,
                ]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_7(
                this,
                Invocation.method(#createTransformedMasterKey, [
                  masterPassword,
                  secretKey,
                  salt,
                ]),
              ),
            ),
          )
          as _i11.Future<_i7.ProtectedValue>);

  @override
  _i11.Future<_i7.ProtectedValue> createStretchedMasterKey(
    _i7.ProtectedValue? transformedMasterKey,
    _i12.Uint8List? instanceId,
    _i12.Uint8List? masterSeed,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStretchedMasterKey, [
              transformedMasterKey,
              instanceId,
              masterSeed,
            ]),
            returnValue: _i11.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_7(
                this,
                Invocation.method(#createStretchedMasterKey, [
                  transformedMasterKey,
                  instanceId,
                  masterSeed,
                ]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_7(
                this,
                Invocation.method(#createStretchedMasterKey, [
                  transformedMasterKey,
                  instanceId,
                  masterSeed,
                ]),
              ),
            ),
          )
          as _i11.Future<_i7.ProtectedValue>);

  @override
  _i11.Future<_i5.AuthEncryptedResult> createProtectedSymmetricKey(
    _i7.ProtectedValue? symmetricKey,
    _i7.ProtectedValue? stretchedMasterKey,
    _i12.Uint8List? nonce,
    _i12.Uint8List? instanceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createProtectedSymmetricKey, [
              symmetricKey,
              stretchedMasterKey,
              nonce,
              instanceId,
            ]),
            returnValue: _i11.Future<_i5.AuthEncryptedResult>.value(
              _FakeAuthEncryptedResult_8(
                this,
                Invocation.method(#createProtectedSymmetricKey, [
                  symmetricKey,
                  stretchedMasterKey,
                  nonce,
                  instanceId,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i11.Future<_i5.AuthEncryptedResult>.value(
                  _FakeAuthEncryptedResult_8(
                    this,
                    Invocation.method(#createProtectedSymmetricKey, [
                      symmetricKey,
                      stretchedMasterKey,
                      nonce,
                      instanceId,
                    ]),
                  ),
                ),
          )
          as _i11.Future<_i5.AuthEncryptedResult>);

  @override
  _i11.Future<String> generateUUID() =>
      (super.noSuchMethod(
            Invocation.method(#generateUUID, []),
            returnValue: _i11.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#generateUUID, []),
              ),
            ),
            returnValueForMissingStub: _i11.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#generateUUID, []),
              ),
            ),
          )
          as _i11.Future<String>);

  @override
  _i11.Future<_i7.ProtectedValue> generateRandomBytes({int? length = 32}) =>
      (super.noSuchMethod(
            Invocation.method(#generateRandomBytes, [], {#length: length}),
            returnValue: _i11.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_7(
                this,
                Invocation.method(#generateRandomBytes, [], {#length: length}),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_7(
                this,
                Invocation.method(#generateRandomBytes, [], {#length: length}),
              ),
            ),
          )
          as _i11.Future<_i7.ProtectedValue>);

  @override
  _i11.Future<_i8.AppConfig> generateAppConfig(
    _i7.ProtectedValue? masterPassword,
    _i7.ProtectedValue? secretKey,
    String? instanceId,
    _i12.Uint8List? transformSeed,
    _i12.Uint8List? masterSeed,
    _i7.ProtectedValue? symmetricKey,
    _i12.Uint8List? nonce,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateAppConfig, [
              masterPassword,
              secretKey,
              instanceId,
              transformSeed,
              masterSeed,
              symmetricKey,
              nonce,
            ]),
            returnValue: _i11.Future<_i8.AppConfig>.value(
              _FakeAppConfig_9(
                this,
                Invocation.method(#generateAppConfig, [
                  masterPassword,
                  secretKey,
                  instanceId,
                  transformSeed,
                  masterSeed,
                  symmetricKey,
                  nonce,
                ]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i8.AppConfig>.value(
              _FakeAppConfig_9(
                this,
                Invocation.method(#generateAppConfig, [
                  masterPassword,
                  secretKey,
                  instanceId,
                  transformSeed,
                  masterSeed,
                  symmetricKey,
                  nonce,
                ]),
              ),
            ),
          )
          as _i11.Future<_i8.AppConfig>);

  @override
  _i11.Future<_i7.ProtectedValue> decryptSymmetricKey(
    _i7.ProtectedValue? masterPassword,
    _i7.ProtectedValue? secretKey,
    _i8.AppConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptSymmetricKey, [
              masterPassword,
              secretKey,
              config,
            ]),
            returnValue: _i11.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_7(
                this,
                Invocation.method(#decryptSymmetricKey, [
                  masterPassword,
                  secretKey,
                  config,
                ]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i7.ProtectedValue>.value(
              _FakeProtectedValue_7(
                this,
                Invocation.method(#decryptSymmetricKey, [
                  masterPassword,
                  secretKey,
                  config,
                ]),
              ),
            ),
          )
          as _i11.Future<_i7.ProtectedValue>);
}
